name: zrepository
description: your simple streaming NOSQL repository.
version: 0.0.6
homepage: https://github.com/GuilhermeZety/zrepository

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  streaming_shared_preferences: ^2.0.0
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter: